#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$($shome/script/version | jq -r '.aws_codedeploy_agent')" != "$AWS_CODEDEPLOY_AGENT_VERSION" ]]; then
    return 1
  fi

  return 0
}

main "$@"
